name: Build & Test

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}-tests
  cancel-in-progress: true

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -v -race ./...
